### PR TITLE
update deps on the analyzer and code_transformers

### PR DESCRIPTION
**Pull request by jakemac53**
I do see 3 failing tests, but these appear to be failing on master as well:

```
---------- Failed tests:
  ../test/mixin_application_test.dart
  ../test/new_instance_html_test.dart
  ../build/test/*_test.dart
```

### CODE REVIEW

**Comment by jakemac53** [comment]
also fwiw, all polymer tests pass with this change

**Comment by eernstg** [comment]
I just checked out this update. We have the following test failures (all well-known):

---------- Failed tests:
  ../test/mixin_application_test.dart: blocked on sdk issue 25344.
  ../test/new_instance_html_test.dart: blocked on sdk issue 18541.
  ../build/test/mixin_application_test.dart: blocked on sdk issue 25344.
  ../build/test/new_instance_html_test.dart: blocked on sdk issue 18541.

I had to change a couple of things to make the static checks of reflectable clean with the new versions of other packages. @jakemac53, do you want to enhance this PR with these changes, or how do we get that part included? (I don't know of a way to create a PR-for-a-PR.)
```
diff --git a/reflectable/lib/src/transformer_implementation.dart b/reflectable/lib/src/transformer_implementation.dart
index 828bf8f..e55c193 100644
--- a/reflectable/lib/src/transformer_implementation.dart
+++ b/reflectable/lib/src/transformer_implementation.dart
@@ -427,7 +427,7 @@ class ClassElementEnhancedSet implements Set<ClassElement> {
   }

   @override
-  Set<ClassElement> difference(Set<ClassElement> other) {
+  Set<ClassElement> difference(Set<Object> other) {
     return classElements.items.toSet().difference(other);
   }

@@ -4852,10 +4852,6 @@ class MixinApplication implements ClassElement {
       throw unreachableError("documentationComment");

   @override
-  @deprecated
-  get docRange => throw unreachableError("docRange");
-
-  @override
   CompilationUnit get unit => throw unreachableError("unit");

   @override
```

**Comment by eernstg** [comment]
I'll add the adjustments in a separate CL.

**Comment by jakemac53** [comment]
Fwiw, you can do a pull request to any branch which is how you would do a "pr to a pr" in the future :)

**Comment by eernstg** [comment]
OK, good to know! ;-) 
Reflectable 1.0.1 is now published.

**Pull request merged**
