### PR TITLE
Add isEnum to reflectable ClassMirror

### PR DESCRIPTION
**Pull request by luisvt**
Add the `isEnum` method to reflectable `ClassMirror` class. In this way we will be able to check if the object is an enum

### CODE REVIEW

**Comment by sigurdm** [comment]
Thanks for the contribution!

Would you mind rebasing this to be a single commit? Then we can merge it and afterwards put in an implementation in the transformer.

**Comment by luisvt** [comment]
ok

**Comment by luisvt** [comment]
done, there is only one commit now

**Comment by eernstg** [comment]
Thanks a lot! I'm currently debugging other stuff, but I'll look into this as soon as possible.

**Comment by eernstg** [comment]
With the CLA issue resolved, we can finally handle this PR! ;-)

The PR was merged manually, because of conflicts that had arisen in the mean time. The resulting commit is 63109c6b6372e5c5ee293b46fcd0054256633616.

**Pull request closed without merging**
