### PR TITLE
MetadataCapability Build Failind when class don't have constructor

### PR DESCRIPTION
**Pull request by luisvt**
When working with metadataCapabilty, I just find a bug that if the reflected class didn't have constructor, the reflectable transformer failed during build. This was caused because a null pointer exception due to node being null. 

Althought I create a patch I'm not completely sure if that patch is correct, please review and do the correct patch.

### CODE REVIEW

**Comment by eernstg** [comment]
Hello Luis,
we haven't forgotten, we're just busy. Will return to this issue as soon as possible.

**Comment by sigurdm** [comment]
The test-case that is included does not seem to give any problems.
Could you post an example of a test that shows the crash?

**Comment by luisvt** [comment]
What do you mean?

To see the problem you should run the file `test_reflectable/tool/run_tests`. If you run it without the changes on `reflectable/lib/src/transformer_implementation.dart` the tests will fail giving null pointer exceptions doubt to classes don't have declared constructor.

**Comment by sigurdm** [comment]
If I take this program:
```
import "package:reflectable/reflectable.dart";
import "package:unittest/unittest.dart";

class MyReflectableWithMetaCap extends Reflectable {
  const MyReflectableWithMetaCap()
      : super(metadataCapability, invokingCapability, declarationsCapability);
}

const myReflectableWithMetaCap = const MyReflectableWithMetaCap();

class AnnotationClass {
  const AnnotationClass();
}

@myReflectableWithMetaCap
class AnnotatedWithoutConstructor {
  @AnnotationClass()
  String someField;
}

main() {
  test("Annotated Capability", () {
    var awcMirror =
        myReflectableWithMetaCap.reflectType(AnnotatedWithoutConstructor);
    expect(awcMirror.declarations['someField'].metadata,
        equals([const AnnotationClass()]));
  });
}
```

And run it through the transformer with the current master branch (e81397deb73ccc8d4e1c074a807bd4fc053fcbfa) it seems to transform, and run without problems.

**Comment by sigurdm** [comment]
And if I check out your branch, comment out the line with the fix, and use test_reflectable/run_tests I also don't see the null-pointer exception.

**Comment by luisvt** [comment]
The error that I was receiving after doing `pub build --mode=debug test` inside `test_reflectable` folder was this:

```
Build error:
Transform Reflectable on test_reflectable|ReflectableTransformed threw error: The null object does not have a getter 'metadata'.

NoSuchMethodError: method not found: 'metadata'
Receiver: null
Arguments: []
dart:core-patch/object_patch.dart 42                             Object._noSuchMethod
dart:core-patch/object_patch.dart 45                             Object.noSuchMethod
package:reflectable/src/transformer_implementation.dart 1729:51  _extractMetadataCode
package:reflectable/src/transformer_implementation.dart 422:24   _ReflectorDomain._generateCode.<fn>
dart:_internal/iterable.dart 390                                 MappedIterator.moveNext
dart:core-patch/growable_array.dart 189                          List.addAll
package:reflectable/src/transformer_implementation.dart 449:9    _ReflectorDomain._generateCode
package:reflectable/src/transformer_implementation.dart 46:24    ReflectionWorld.generateCode.<fn>
dart:_internal/iterable.dart 413                                 MappedListIterable.elementAt
dart:_internal/iterable.dart 155                                 ListIterable.join
package:reflectable/src/transformer_implementation.dart 1588:50  _formatAsMap
package:reflectable/src/transformer_implementation.dart 44:12    ReflectionWorld.generateCode
package:reflectable/src/transformer_implementation.dart 1388:25  TransformerImplementation._reflectionWorldSource
package:reflectable/src/transformer_implementation.dart 1498:40  TransformerImplementation.apply.<async>
dart:async/zone.dart 1166                                        _RootZone.runUnary
dart:async/future_impl.dart 494                                  _Future._propagateToListeners.handleValueCallback
dart:async/future_impl.dart 577                                  _Future._propagateToListeners
dart:async/future_impl.dart 368                                  _Future._completeWithValue
dart:async/future_impl.dart 422                                  _Future._asyncComplete.<fn>
dart:async/schedule_microtask.dart 43                            _microtaskLoop
dart:async/schedule_microtask.dart 52                            _microtaskLoopEntry
dart:isolate-patch/isolate_patch.dart 96                         _runPendingImmediateCallback
dart:isolate-patch/isolate_patch.dart 149                        _RawReceivePortImpl._handleMessage

dart:core                                                        Object.noSuchMethod
package:reflectable/src/transformer_implementation.dart 1729:51  _extractMetadataCode
package:reflectable/src/transformer_implementation.dart 422:24   _ReflectorDomain._generateCode.<fn>
dart:core                                                        List.addAll
package:reflectable/src/transformer_implementation.dart 449:9    _ReflectorDomain._generateCode
package:reflectable/src/transformer_implementation.dart 46:24    ReflectionWorld.generateCode.<fn>
dart:_internal                                                   ListIterable.join
package:reflectable/src/transformer_implementation.dart 1588:50  _formatAsMap
package:reflectable/src/transformer_implementation.dart 44:12    ReflectionWorld.generateCode
package:reflectable/src/transformer_implementation.dart 1388:25  TransformerImplementation._reflectionWorldSource
package:reflectable/src/transformer_implementation.dart 1498:40  TransformerImplementation.apply.<async>

Build failed.
```

It looks that this error was solved with new version of reflectable.

**Comment by eernstg** [comment]
I believe that the `null.metadata` problem reported and addressed in this pull request has been handled already, so I'll close it. Thanks for your input!

**Pull request closed without merging**
